### ISSUE TITLE
get_traffic.py Syntax Error?

### ISSUE THREAD

**Issue by hessevans** [tejasa97/github_traffic#5]
File "get_traffic.py", line 59
    print(f"Extracting repo stats of '{self.user_name}'...")
                                                                                         ^
SyntaxError: invalid syntax

Would love to get this working

**Comment by astrochun** [comment]
What version of Python are you using? This is f-string and thus you need 3.6+.

**Comment by tejasa97** [comment]
you need python 3.6 +
